---
swagger: "2.0"
info:
  description: "This is a Swagger visualization of DLT Smart Contract API"
  version: "1.0.5"
  title: "DLT Gateway"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ggogos@iti.gr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "auroralh2020.github.io"
tags:
- name: "contract"
  description: "Smart Contract object base functionality"
- name: "item"
  description: "Item object update inside an existing Smart Contract"
schemes:
- "http"
paths:
  /contract/propose:
    post:
      tags:
      - "contract"
      summary: "Org1 proposes a Contract to Org2"
      description: ""
      operationId: "proposeContract"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the pet"
        required: true
        schema:
          $ref: "#/definitions/Contract"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/accept:
    post:
      tags:
      - "contract"
      summary: "Org2 accept contract from Org1"
      description: ""
      operationId: "acceptContract"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "contract_id"
        in: "path"
        description: "ID of contracted to be accepted"
        required: true
        type: "string"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"

securityDefinitions:
  AuthorizationHeader:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Bearer Token"
definitions:
  Contract:
    type: "object"
    properties:
      contract_id:
        type: "string"
      contract_type:
        type: "string"
        description: "Contract Type"
        enum:
        - "private"
        - "community"
      orgs:
        type: "array"
        format: "string"
      items:
        $ref: "#/definitions/Item"
  Item:
    type: "object"
    properties:
      enabled:
        type: "boolean"
      write:
        type: "boolean"
      object_id:
        type: "string"
      org_id:
        type: "string"
      object_type:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
