---
swagger: "2.0"
info:
  description: "This is a Swagger visualization of DLT Smart Contract API"
  version: "1.0.5"
  title: "DLT Gateway"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ggogos@iti.gr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "auroralh2020.github.io"
tags:
- name: "contract"
  description: "Smart Contract object base functionality"
- name: "item"
  description: "Item object update inside an existing Smart Contract"
schemes:
- "http"
paths:
  /contract/propose:
    post:
      tags:
      - "contract"
      summary: "Org1 proposes a Contract to Org2"
      description: ""
      operationId: "proposeContract"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Smart Contract object for proposal"
        required: true
        schema:
          $ref: "#/definitions/Contract"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/accept/{contract_id}:
    post:
      tags:
      - "contract"
      summary: "Org2 accepts contract from Org1"
      description: ""
      operationId: "acceptContract"
      produces:
      - "application/json"
      parameters:
      - name: "contract_id"
        in: "path"
        description: "ID of the contract to be accepted"
        required: true
        type: "string"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/reject/{contract_id}:
    post:
      tags:
      - "contract"
      summary: "Org2 rejects contract from Org1"
      description: ""
      operationId: "rejectContract"
      produces:
      - "application/json"
      parameters:
      - name: "contract_id"
        in: "path"
        description: "ID of the contract to be rejected"
        required: true
        type: "string"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"   
  /contract/delete/{contract_id}:
    delete:
      tags:
      - "contract"
      summary: "Deletion of an existing contract from either Orgs"
      description: ""
      operationId: "deleteContract"
      produces:
      - "application/json"
      parameters:
      - name: "contract_id"
        in: "path"
        description: "ID of the contract to be deleted"
        required: true
        type: "string"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/{contract_id}:
    get:
      tags:
      - "contract"
      summary: "Contract object by ID"
      description: "Returns a contract oject"
      operationId: "getContractByID"
      produces:
      - "application/json"
      parameters:
      - name: "contract_id"
        in: "path"
        description: "ID of contract to return"
        required: true
        type: "string"
      responses:
        200:
          description: "Status OK"
          schema:
            $ref: "#/definitions/Contract"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/list:
    get:
      tags:
      - "contract"
      summary: "Returns all contracts of Org"
      description: "Returns contract objects"
      operationId: "contractList"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Status OK"
          schema:
            $ref: "#/definitions/Contract"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /contract/list/IDs:
    get:
      tags:
      - "contract"
      summary: "Returns all contract IDs of Org"
      description: "Returns string array"
      operationId: "contractListIDs"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Status OK"
          schema:
            $ref: "#/definitions/ContractIDs"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"
  /item/update:
    post:
      tags:
      - "item"
      summary: "Org updates its items in existing contract"
      description: ""
      operationId: "updateItem"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Item object for update"
        required: true
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"        
  /item/add:
    post:
      tags:
      - "item"
      summary: "Org adds a new item in existing contract"
      description: ""
      operationId: "addItem"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Item object for addition"
        required: true
        schema:
          $ref: "#/definitions/Item"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"        
  /item/delete:
    delete:
      tags:
      - "item"
      summary: "Org deletes its items in existing contract"
      description: ""
      operationId: "deleteItem"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Item object for deletion"
        required: true
        schema:
          $ref: "#/definitions/DeleteItem"
      responses:
        200:
          description: "Status OK"
        401:
          description: "Unauthorized"
        405:
          description: "Invalid input"
        404:
          description: "Contract not found"  
      security:
      - contract_auth:
        - "write:contract"
        - "read:contract"                  
        
securityDefinitions:
  AuthorizationHeader:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Bearer Token"
definitions:
  Contract:
    type: "object"
    properties:
      contract_id:
        type: "string"
      contract_type:
        type: "string"
        description: "Contract Type"
        enum:
        - "private"
        - "community"
      orgs:
        type: "array"
        format: "string"
      items:
        $ref: "#/definitions/Item"
  Item:
    type: "object"
    properties:
      enabled:
        type: "boolean"
      write:
        type: "boolean"
      object_id:
        type: "string"
      org_id:
        type: "string"
      object_type:
        type: "string"
  DeleteItem:
    type: "object"
    properties:
      contract_id:
        type: "string"
      object_id:
        type: "string"      
  ContractIDs:
  type: "array"
  format: "string"
    
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
